{
 "title": "Homelab — pfSense",
 "description": "A Grafana dashboard to monitor pfSense via the node_exporter (Prometheus). Adapted from https://github.com/VictorRobellini/pfSense-Dashboard",
 "tags": [
  "homelab",
  "pfsense"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"pfsense\"}, host)"
    }
   },
   {
    "name": "Disk",
    "label": "Disk",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{host=~\"$Host\"}, device)"
    }
   },
   {
    "name": "WAN",
    "label": "Interface",
    "query": "WAN : vtnet0.5,LAN : vtnet0,Guest : vtnet0.30,IOT : vtnet0.6,BWAN : vtnet0.7,VPN : tun_wg0,PROTON : tun_wg1"
   },
   {
    "name": "CPU",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{host=~\"$Host\"}, cpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "y": 0, "w": 24, "h": 1, "x": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "y": 1, "w": 3, "h": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (cpu) (node_cpu_seconds_total{host=~\"$Host\"}))"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "y": 1, "w": 3, "h": 6, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{host=~\"$Host\", mode=\"idle\"}[$__rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "y": 1, "w": 9, "h": 6, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu_seconds_total{host=~\"$Host\", cpu=~\"$CPU\", mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "System Information",
   "type": "table",
   "gridPos": { "y": 7, "w": 24, "h": 4, "x": 0 },
   "targets": [
    {
     "expr": "node_uname_info{host=~\"$Host\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "y": 1, "w": 9, "h": 6, "x": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{host=~\"$Host\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{host=~\"$Host\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{host=~\"$Host\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "y": 4, "w": 3, "h": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{host=~\"$Host\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "y": 11, "w": 12, "h": 6, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{host=~\"$Host\", device=~\"$Disk\"} / node_filesystem_size_bytes{host=~\"$Host\", device=~\"$Disk\"}) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Ram",
   "type": "timeseries",
   "gridPos": { "y": 11, "w": 12, "h": 6, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{host=~\"$Host\"} - node_memory_free_bytes{host=~\"$Host\"} - node_memory_inactive_bytes{host=~\"$Host\"} - node_memory_cache_bytes{host=~\"$Host\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_free_bytes{host=~\"$Host\"} + node_memory_inactive_bytes{host=~\"$Host\"} + node_memory_cache_bytes{host=~\"$Host\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_memory_free_bytes{host=~\"$Host\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_buffer_bytes{host=~\"$Host\"}",
     "legendFormat": "buffered"
    },
    {
     "expr": "node_memory_cache_bytes{host=~\"$Host\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_swap_used_bytes{host=~\"$Host\"}",
     "legendFormat": "swap_used"
    },
    {
     "expr": "node_memory_swap_size_bytes{host=~\"$Host\"} - node_memory_swap_used_bytes{host=~\"$Host\"}",
     "legendFormat": "swap_free"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "y": 17, "w": 24, "h": 1, "x": 0 } },
  {
   "title": "Interface summary",
   "type": "table",
   "gridPos": { "y": 18, "w": 24, "h": 10, "x": 0 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_receive_bytes_total{host=~\"$Host\", device!~\"lo0|lo|enc0|pflog0|pfsync0\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_transmit_bytes_total{host=~\"$Host\", device!~\"lo0|lo|enc0|pflog0|pfsync0\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_receive_packets_total{host=~\"$Host\", device!~\"lo0|lo|enc0|pflog0|pfsync0\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_transmit_packets_total{host=~\"$Host\", device!~\"lo0|lo|enc0|pflog0|pfsync0\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_receive_drop_total{host=~\"$Host\", device!~\"lo0|lo|enc0|pflog0|pfsync0\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_transmit_drop_total{host=~\"$Host\", device!~\"lo0|lo|enc0|pflog0|pfsync0\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_receive_errs_total{host=~\"$Host\", device!~\"lo0|lo|enc0|pflog0|pfsync0\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_transmit_errs_total{host=~\"$Host\", device!~\"lo0|lo|enc0|pflog0|pfsync0\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    }
   ]
  },
  {
   "title": "Selected Interfaces - ${WAN:text}",
   "type": "row",
   "gridPos": { "y": 28, "w": 24, "h": 1, "x": 0 },
   "repeat": "WAN"
  },
  {
   "title": "Interface summary",
   "type": "table",
   "gridPos": { "y": 29, "w": 24, "h": 6, "x": 0 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_receive_bytes_total{host=~\"$Host\", device=~\"$WAN\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_transmit_bytes_total{host=~\"$Host\", device=~\"$WAN\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_receive_packets_total{host=~\"$Host\", device=~\"$WAN\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_transmit_packets_total{host=~\"$Host\", device=~\"$WAN\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_receive_drop_total{host=~\"$Host\", device=~\"$WAN\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_transmit_drop_total{host=~\"$Host\", device=~\"$WAN\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_receive_errs_total{host=~\"$Host\", device=~\"$WAN\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(node_network_transmit_errs_total{host=~\"$Host\", device=~\"$WAN\"}, \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")"
    }
   ]
  },
  {
   "title": "Traffic Bytes/sec - ${WAN:text}",
   "type": "timeseries",
   "gridPos": { "y": 35, "w": 12, "h": 8, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(rate(node_network_receive_bytes_total{host=~\"$Host\", device=~\"$WAN\"}[$__rate_interval]), \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")",
     "legendFormat": "{{device}} rx_bps"
    },
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(rate(node_network_transmit_bytes_total{host=~\"$Host\", device=~\"$WAN\"}[$__rate_interval]), \"device\", \"WAN\", \"device\", \"^vtnet0\\\\.5$\"), \"device\", \"LAN\", \"device\", \"^vtnet0$\"), \"device\", \"Guest\", \"device\", \"^vtnet0\\\\.30$\"), \"device\", \"IOT\", \"device\", \"^vtnet0\\\\.6$\"), \"device\", \"BWAN\", \"device\", \"^vtnet0\\\\.7$\"), \"device\", \"VPN\", \"device\", \"^tun_wg0$\"), \"device\", \"PROTON\", \"device\", \"^tun_wg1$\")",
     "legendFormat": "{{device}} tx_bps"
    }
   ]
  },
  {
   "title": "Traffic Bits/sec - ${WAN:text}",
   "type": "stat",
   "gridPos": { "y": 35, "w": 4, "h": 4, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{host=~\"$Host\", device=~\"$WAN\"}[$__rate_interval])) * 8",
     "legendFormat": "bytes_recv"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{host=~\"$Host\", device=~\"$WAN\"}[$__rate_interval])) * 8",
     "legendFormat": "bytes_sent"
    }
   ]
  },
  {
   "title": "Totals - ${WAN:text}",
   "type": "stat",
   "gridPos": { "y": 39, "w": 4, "h": 4, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(node_network_receive_bytes_total{host=~\"$Host\", device=~\"$WAN\"})",
     "legendFormat": "bytes_recv"
    },
    {
     "expr": "sum(node_network_transmit_bytes_total{host=~\"$Host\", device=~\"$WAN\"})",
     "legendFormat": "bytes_sent"
    }
   ]
  },
  {
   "title": "Throughput - ${WAN:text}",
   "type": "timeseries",
   "gridPos": { "y": 35, "w": 8, "h": 8, "x": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{host=~\"$Host\", device=~\"$WAN\"}[$__rate_interval]))",
     "legendFormat": "rx_pps"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets_total{host=~\"$Host\", device=~\"$WAN\"}[$__rate_interval]))",
     "legendFormat": "tx_pps"
    }
   ]
  }
 ]
}