{
 "title": "pfSense (Flux)",
 "description": "See the github link for the most up-to-date dashboard.\r\n\r\nA Grafana dashboard built to monitor pfSense that relies on influx and Telegraf.  All artifacts and instructions are maintained in github at https://github.com/VictorRobellini/pfSense-Dashboard",
 "tags": [
  "pfsense",
  "flux"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"pfsense\", tag: \"host\", predicate: (r) => r._measurement == \"pf\")"
   },
   {
    "name": "Disk",
    "label": "Disk",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"pfsense\", tag: \"device\", predicate: (r) => r._measurement == \"disk\" and r.host =~ /${Host:regex}/)"
   },
   {
    "name": "WAN",
    "label": "Interface",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"pfsense\", tag: \"interface\", predicate: (r) => r._measurement == \"net\" and r.host =~ /${Host:regex}/ and r.interface != \"all\" and r.interface != \"lo0\")"
   },
   {
    "name": "CPU",
    "label": "CPU",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"pfsense\", tag: \"cpu\", predicate: (r) => r._measurement == \"cpu\" and r.host =~ /${Host:regex}/ and r.cpu != \"cpu-total\")"
   }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "y": 0, "w": 24, "h": 1, "x": 0 } },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "y": 1, "w": 3, "h": 3, "x": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\" and r._field == \"n_users\" and r.host =~ /${Host:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "y": 1, "w": 3, "h": 6, "x": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r.cpu == \"cpu-total\" and r._field == \"usage_idle\" and r.host =~ /${Host:regex}/)\n  |> mean()\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "y": 1, "w": 9, "h": 6, "x": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage_idle\" and r.cpu =~ /${CPU:regex}/ and r.host =~ /${Host:regex}/)\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"cpu\"])"
    }
   ]
  },
  {
   "title": "Process Information",
   "type": "table",
   "gridPos": { "y": 7, "w": 24, "h": 4, "x": 0 },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"processes\" and r.host =~ /${Host:regex}/)\n  |> last()\n  |> keep(columns: [\"_field\",\"_value\"])\n  |> rename(columns: {_field: \"state\", _value: \"count\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "y": 1, "w": 9, "h": 6, "x": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\" and (r._field == \"load1\" or r._field == \"load5\" or r._field == \"load15\") and r.host =~ /${Host:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "y": 4, "w": 3, "h": 3, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\" and r._field == \"uptime\" and r.host =~ /${Host:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "PF Information",
   "type": "table",
   "gridPos": { "y": 11, "w": 24, "h": 5, "x": 0 },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"pf\" and r.host =~ /${Host:regex}/)\n  |> last()\n  |> keep(columns: [\"_field\",\"_value\"])\n  |> rename(columns: {_field: \"counter\", _value: \"value\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "y": 16, "w": 12, "h": 6, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\" and r.device =~ /${Disk:regex}/ and r.host =~ /${Host:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Ram",
   "type": "timeseries",
   "gridPos": { "y": 16, "w": 12, "h": 6, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\" and (r._field == \"used\" or r._field == \"available\" or r._field == \"free\" or r._field == \"buffered\" or r._field == \"cached\") and r.host =~ /${Host:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"swap\" and (r._field == \"used\" or r._field == \"free\") and r.host =~ /${Host:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: \"swap_\" + r._field }))"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "y": 22, "w": 24, "h": 1, "x": 0 } },
  {
   "title": "Interface summary",
   "type": "table",
   "gridPos": { "y": 23, "w": 24, "h": 10, "x": 0 },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\" and r.host =~ /${Host:regex}/ and r.interface != \"all\")\n  |> filter(fn: (r) => r._field == \"bytes_recv\" or r._field == \"bytes_sent\" or r._field == \"packets_recv\" or r._field == \"packets_sent\" or r._field == \"drop_in\" or r._field == \"drop_out\" or r._field == \"err_in\" or r._field == \"err_out\")\n  |> last()\n  |> keep(columns: [\"interface\",\"_field\",\"_value\"])\n  |> group()\n  |> pivot(rowKey: [\"interface\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  { "title": "Selected Interfaces - $WAN", "type": "row", "gridPos": { "y": 33, "w": 24, "h": 1, "x": 0 }, "repeat": "WAN" },
  {
   "title": "Interface summary",
   "type": "table",
   "gridPos": { "y": 34, "w": 24, "h": 6, "x": 0 },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\" and r.interface =~ /${WAN:regex}/ and r.host =~ /${Host:regex}/)\n  |> filter(fn: (r) => r._field == \"bytes_recv\" or r._field == \"bytes_sent\" or r._field == \"packets_recv\" or r._field == \"packets_sent\" or r._field == \"drop_in\" or r._field == \"drop_out\" or r._field == \"err_in\" or r._field == \"err_out\")\n  |> last()\n  |> keep(columns: [\"interface\",\"_field\",\"_value\"])\n  |> group()\n  |> pivot(rowKey: [\"interface\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Traffic Bytes/sec - $WAN",
   "type": "timeseries",
   "gridPos": { "y": 40, "w": 12, "h": 8, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\" and r._field == \"bytes_recv\" and r.interface =~ /${WAN:regex}/ and r.host =~ /${Host:regex}/)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"rx_bps\")\n  |> group(columns: [\"interface\",\"_field\"])"
    },
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\" and r._field == \"bytes_sent\" and r.interface =~ /${WAN:regex}/ and r.host =~ /${Host:regex}/)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"tx_bps\")\n  |> group(columns: [\"interface\",\"_field\"])"
    }
   ]
  },
  {
   "title": "Traffic Bits/sec - $WAN",
   "type": "stat",
   "gridPos": { "y": 40, "w": 4, "h": 4, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\" and (r._field == \"bytes_recv\" or r._field == \"bytes_sent\") and r.interface =~ /${WAN:regex}/ and r.host =~ /${Host:regex}/)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Totals - $WAN",
   "type": "stat",
   "gridPos": { "y": 44, "w": 4, "h": 4, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\" and (r._field == \"bytes_recv\" or r._field == \"bytes_sent\") and r.interface =~ /${WAN:regex}/ and r.host =~ /${Host:regex}/)\n  |> last()\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Throughput - $WAN",
   "type": "timeseries",
   "gridPos": { "y": 40, "w": 8, "h": 8, "x": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\" and r._field == \"packets_recv\" and r.interface =~ /${WAN:regex}/ and r.host =~ /${Host:regex}/)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"rx_pps\")\n  |> group(columns: [\"_field\"])"
    },
    {
     "query": "from(bucket: \"pfsense\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\" and r._field == \"packets_sent\" and r.interface =~ /${WAN:regex}/ and r.host =~ /${Host:regex}/)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> set(key: \"_field\", value: \"tx_pps\")\n  |> group(columns: [\"_field\"])"
    }
   ]
  }
 ]
}