{
 "title": "Homelab — Proxmox",
 "description": "Proxmox Dashboard complete written in Flux w/ Cluster support",
 "tags": [
  "homelab",
  "proxmox"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(pve_node_info, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "Server CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{id=~\"node/$server\"} * 100"
    }
   ]
  },
  {
   "title": "Logical Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_limit{id=~\"node/$server\"}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_size_bytes{id=~\"node/$server\"}"
    }
   ]
  },
  {
   "title": "Not backed up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pve_not_backed_up_total{id=\"cluster/pve\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Storage Pools",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=~\"storage/.+\"} / clamp_min(pve_disk_size_bytes{id=~\"storage/.+\"}, 1) * 100 * on (id) group_left (storage) pve_storage_info{node=~\"$server\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pve_guest_info{node=~\"$server\", type=\"qemu\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pve_up == 1 and on (id) pve_guest_info{node=~\"$server\", type=\"qemu\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total LXCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pve_guest_info{node=~\"$server\", type=\"lxc\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Running LXCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pve_up == 1 and on (id) pve_guest_info{node=~\"$server\", type=\"lxc\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "stat",
   "description": "Memory in use by Host OS, VM's and Containers",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{id=~\"node/$server\"}"
    }
   ]
  },
  {
   "title": "Cluster summary of Resources $server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Running VMs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pve_uptime_seconds{id=~\"qemu/.+\"} * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"qemu\"} and on (id) (pve_up == 1))"
    }
   ]
  },
  {
   "title": "Running LXCs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pve_uptime_seconds{id=~\"lxc/.+\"} * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"lxc\"} and on (id) (pve_up == 1))"
    }
   ]
  },
  { "title": "Memory and CPU usage $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Host CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{id=~\"node/$server\"} * 100",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_size_bytes{id=~\"node/$server\"}",
     "legendFormat": "memtotal"
    },
    {
     "expr": "pve_memory_usage_bytes{id=~\"node/$server\"}",
     "legendFormat": "memused"
    }
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pve_cpu_usage_ratio{id=~\"qemu/.+\"} * 100) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"qemu\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{id=~\"qemu/.+\"} / clamp_min(pve_memory_size_bytes{id=~\"qemu/.+\"}, 1) * 100) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"qemu\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LXC CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pve_cpu_usage_ratio{id=~\"lxc/.+\"} * 100) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"lxc\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LXC memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{id=~\"lxc/.+\"} / clamp_min(pve_memory_size_bytes{id=~\"lxc/.+\"}, 1) * 100) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"lxc\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VM I/O Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_read_bytes_total{id=~\"qemu/.+\"}[$__rate_interval]) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"qemu\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VMs I/O Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_written_bytes_total{id=~\"qemu/.+\"}[$__rate_interval]) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"qemu\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LXC rootfs usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=~\"lxc/.+\"} / clamp_min(pve_disk_size_bytes{id=~\"lxc/.+\"}, 1) * 100 * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"lxc\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VM traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes_total{id=~\"qemu/.+\"}[$__rate_interval]) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"qemu\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VM traffic out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_network_transmit_bytes_total{id=~\"qemu/.+\"}[$__rate_interval]) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"qemu\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LXC traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes_total{id=~\"lxc/.+\"}[$__rate_interval]) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"lxc\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LXC traffic out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_network_transmit_bytes_total{id=~\"lxc/.+\"}[$__rate_interval]) * on (id) group_left (name, node) (pve_guest_info{node=~\"$server\", type=\"lxc\"} and on (id) (pve_up == 1))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Guests without backup",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pve_not_backed_up_info * on (id) group_left (name, node, type) pve_guest_info{node=~\"$server\"}"
    }
   ]
  }
 ]
}