{
 "title": "Homelab — Traefik",
 "description": "Visualizing Traefik Reverse Proxy Stats",
 "tags": [
  "homelab",
  "traefik"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "nas,server,monitor,netboot,postgres"
   },
   { "name": "sampling", "label": "Sampling", "query": "1m,10m,60m" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total{host=\"$host\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total request",
   "type": "stat",
   "gridPos": { "y": 0, "w": 4, "h": 9, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_router_requests_total{host=\"$host\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests per service",
   "type": "timeseries",
   "gridPos": { "y": 0, "w": 20, "h": 9, "x": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(traefik_service_requests_total{host=\"$host\", service=~\"$service\"}[$sampling]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(count_over_time({job=\"traefik\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (service, le) (rate(traefik_service_request_duration_seconds_bucket{host=\"$host\", service=~\"$service\"}[$sampling])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total status code count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(traefik_router_requests_total{host=\"$host\"}[$sampling]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (entrypoint, protocol, method) (traefik_open_connections{host=\"$host\"})",
     "legendFormat": "{{entrypoint}} {{protocol}} {{method}}"
    }
   ]
  },
  {
   "title": "Traefik JSON Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{job=\"traefik\"} | json | line_format \"{{.OriginStatus}} | {{.time}} | {{.RequestAddr}} | {{.ClientHost}} | {{.RequestMethod}} {{.RequestPath}} {{.RequestProtocol}} | {{.request_User_Agent}}\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "maxLines": 800,
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}