- name: Ensure SSH rule exists to prevent lockout
  ansible.builtin.assert:
    that:
      - ufw_rules | selectattr('comment','equalto', 'SSH') | list | length > 0
    fail_msg: "No SSH rule found in ufw_rules! You might lock yourself out."

- name: Resets firewall to installation defaults.
  community.general.ufw:
    state: reset

- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Apply UFW rules from inventory
  community.general.ufw:
    rule: allow
    proto: "{{ item.protocol }}"
    port: "{{ item.port }}"
    comment: "{{ item.comment }}"
  loop: "{{ ufw_rules }}"

- name: Enable UFW with logging
  community.general.ufw:
    state: enabled
    logging: 'on'

- name: Create logrotate config for access
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/logrotate.j2"
    dest: "/etc/logrotate.d/uwf"
    owner: "root"
    group: "root"
    mode: "0644"
  vars:
    log_path: "/var/log/ufw.log"
