---
- name: Create OpenBao directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ openbao_uid }}"
    group: "{{ openbao_gid }}"
    mode: "0750"
  loop:
    - ./data/openbao
    - ./data/openbao/config
    - ./data/openbao/data
    - ./data/openbao/audit

- name: Render OpenBao config
  ansible.builtin.template:
    src: config.hcl.j2
    dest: ./data/openbao/config/config.hcl
    owner: "{{ openbao_uid }}"
    group: "{{ openbao_gid }}"
    mode: "0640"
  register: openbao_config

- name: Create logrotate config for openbao audit log
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/logrotate.j2"
    dest: "/etc/logrotate.d/openbao"
    owner: "root"
    group: "root"
    mode: "0644"
  vars:
    log_path: "{{ ansible_facts.env.PWD }}/data/openbao/audit/audit.log"
    max_size: "{{ openbao_audit_log_max_size }}"
    rotate_count: "{{ openbao_audit_log_rotate_count }}"
    copytruncate: true
