---
- name: Enable SSH service
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started

- name: Create group for ssh
  ansible.builtin.group:
    name: ssh
    state: present

- name: Ensure /etc/ssh/sshd_config.d exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure main sshd_config includes sshd_config.d
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Include /etc/ssh/sshd_config\.d/\*\.conf'
    line: 'Include /etc/ssh/sshd_config.d/*.conf'
    insertafter: BOF
  notify: Validate SSHD configuration
