---
- name: Check if passwords match
  ansible.builtin.assert:
    that:
      - user_password == user_password_confirm
    fail_msg: "Passwords do not match. Please run the playbook again and ensure the passwords match."
    success_msg: "Passwords match."

- name: Create hashed password
  ansible.builtin.set_fact:
    hashed_password: "{{ user_password | password_hash('sha512') }}"

- name: Generate ssh keys
  ansible.builtin.include_tasks: generate_ssh_key.yml

- name: Append new user to default_users
  ansible.builtin.set_fact:
    default_users: >-
      {{ default_user + [{
        'name': new_user,
        'password': hashed_password,
        'key_path': new_user_key_path,
        'robot': false
      }] }}
