---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: "dist"
    autoclean: true
    autoremove: true

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - sudo
      - acl
      - apt-transport-https
      - bat
      - btop
      - ca-certificates
      - curl
      - fd-find
      - git
      - gnupg
      - iputils-ping
      - jq
      - logrotate
      - mc
      - nano
      - ncdu
      - ripgrep
      - ufw
      - unattended-upgrades
      - wget

- name: Install eza
  ansible.builtin.include_tasks: install_eza.yml

- name: Configure automatic upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade::InstallOnShutdown "0";
    owner: "root"
    group: "root"
    mode: "0644"
