---
- name: Create environment
  ansible.builtin.include_tasks: environment.yml

- name: Build ansible-runner image
  community.docker.docker_image:
    name: "{{ ansible_runner.image.split(':')[0] }}"
    tag: "{{ ansible_runner.image.split(':')[1] | default('latest') }}"
    source: build
    build:
      path: "{{ ansible_facts.env.PWD }}/data/ansible-runner/build"
      pull: true
      nocache: "{{ runner_update | default(false) | bool }}"
    force_source: "{{ (runner_update | default(false) | bool) or (ansible_runner_dockerfile.changed | default(false)) }}"
