---
user:
  name: "deploy"
  group: "docker"

loki_ingest_url: "http://loki:3100/loki/api/v1/push"
alloy_metrics_url: "https://prometheus.example.com/api/v1/write"
alloy_scrape_interval: "15s"
current_host: "example"

alloy:
  static: "172.20.0.70"
  syslog:
    format: rfc3164
    devices:
      - { name: firewall, port: 1514, protocols: ["udp"] }
      - { name: accesspoint, port: 1515, protocols: ["udp"] }
  http_checks:
    - name: "example-service"
      internal_url: "http://example:8080/health"
      url: "https://service.example.com"

kestra:
  metrics_port: "8081"
openbao:
  port: "8200"
postgres:
  port: 5432
  adm_user: "postgres"
  adm_pass: "changeme"
docker_storage_driver: ""
