---
- name: Create directories if they don't exist
  ansible.builtin.file:
    path: ./data/netboot
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: Create container-owned directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: "0755"
  loop:
    - ./data/netboot/config
    - ./data/netboot/assets

- name: Create container
  community.docker.docker_container:
    name: netbootxyz
    image: ghcr.io/netbootxyz/netbootxyz
    restart_policy: unless-stopped
    networks:
      - name: proxy
        ipv4_address: "{{ ip['netbootxyz'] }}"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TFTPD_OPTS: "--tftp-single-port"
    volumes:
      - ./data/netboot/config:/config
      - ./data/netboot/assets:/assets
    labels:
      traefik.enable: "true"
      traefik.http.routers.netbootxyz.entrypoints: "https"
      traefik.http.routers.netbootxyz.rule: "{{ netboot.host }}"
      traefik.http.routers.netbootxyz.tls: "true"
      traefik.http.routers.netbootxyz.middlewares: "chain-auth@file"
      traefik.http.routers.netbootxyz.service: "netbootxyz"
      traefik.http.services.netbootxyz.loadbalancer.server.port: "{{ netboot.port }}"
      traefik.http.routers.netbootxyz-assets.entrypoints: "https"
      traefik.http.routers.netbootxyz-assets.rule: "{{ netboot.assets_host }}"
      traefik.http.routers.netbootxyz-assets.tls: "true"
      traefik.http.routers.netbootxyz-assets.middlewares: "chain-no-auth@file"
      traefik.http.routers.netbootxyz-assets.service: "netbootxyz-assets"
      traefik.http.services.netbootxyz-assets.loadbalancer.server.port: "80"
    ports:
      - "69:69/udp"
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 10s

- name: Wait for netboot to be ready
  community.docker.docker_container_info:
    name: netbootxyz
  register: netboot_info
  until: netboot_info.container.State.Health.Status == 'healthy'
  retries: 12
  delay: 10
