---
- name: Create directories if they don't exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"
  loop:
    - "./data/kuma"
    - "./data/kuma/data"

- name: Add uptime-kuma
  community.docker.docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:latest
    pull: true
    state: started
    restart_policy: always
    networks:
      - name: proxy
    dns_servers:
      - "{{ default.dns }}"
    env:
      TZ: "Europe/Belgrade"
    volumes:
      - ./data/kuma/data:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.kuma.entrypoints: "https"
      traefik.http.routers.kuma.rule: "{{ kuma.host }}"
      traefik.http.routers.kuma.tls: "true"
      traefik.http.services.kuma.loadbalancer.server.port: "{{ kuma.port }}"
