---
- name: Get InfluxDB org ID
  ansible.builtin.uri:
    url: "{{ influxdb.url }}/api/v2/orgs?org={{ influxdb.organization }}"
    method: GET
    headers:
      Authorization: "Token {{ influxdb.api_token }}"
    return_content: true
  register: influxdb_org
  delegate_to: localhost

- name: Check if bucket exists
  ansible.builtin.uri:
    url: "{{ influxdb.url }}/api/v2/buckets?name=telegraf-{{ current_host }}&org={{ influxdb.organization }}"
    method: GET
    headers:
      Authorization: "Token {{ influxdb.api_token }}"
    return_content: true
    status_code: [200, 404]
  register: influxdb_bucket_check
  delegate_to: localhost

- name: Create bucket for this host
  ansible.builtin.uri:
    url: "{{ influxdb.url }}/api/v2/buckets"
    method: POST
    headers:
      Authorization: "Token {{ influxdb.api_token }}"
    body_format: json
    body:
      orgID: "{{ influxdb_org.json.orgs[0].id }}"
      name: "telegraf-{{ current_host }}"
      retentionRules: []
    status_code: 201
  when: influxdb_bucket_check.status == 404 or influxdb_bucket_check.json.buckets | length == 0
  delegate_to: localhost
