- name: Create directory if they don't exist
  ansible.builtin.file:
    path: "./data/telegraf"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: "Generate config"
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: ./data/telegraf/telegraf.conf
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'

- name: Deploy container
  community.docker.docker_container:
    name: telegraf
    image: telegraf:latest
    restart_policy: unless-stopped
    user: telegraf:{{ pgid }}
    groups:
      - "video"
    # recreate: yes
    networks:
      - name: proxy
    env:
      TZ: "Europe/Belgrade"
      HOST_ETC: "/hostfs/etc"
      HOST_PROC: "/hostfs/proc"
      HOST_SYS: "/hostfs/sys"
      HOST_VAR: "/hostfs/var"
      HOST_RUN: "/hostfs/run"
      HOST_MOUNT_PREFIX: "/hostfs"
    volumes:
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
      - './data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
