---
user:
  name: "deploy"
  group: "docker"

prometheus:
  static: "172.20.0.30"
  host: "Host(`prometheus.example.com`)"
  domain: "prometheus.example.com"
  url: "https://prometheus.example.com"
  port: "9090"

prometheus_retention: "90d"

pve:
  api_host: "192.0.2.10:8006"

pfsense_exporter:
  target: "node-router.example.com"
