---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: ./data/public_ip_tracker
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0744"

- name: Check if the file exists
  ansible.builtin.stat:
    path: ./data/public_ip_tracker/app.log
  register: file_check

- name: Touch app.log file
  ansible.builtin.file:
    path: ./data/public_ip_tracker/app.log
    state: touch
    mode: "0755"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: not file_check.stat.exists

- name: Run Docker container from built image
  community.docker.docker_container:
    name: public_ip_tracker
    image: nemanjaslijepcevic/public_ip_tracker:latest
    state: started
    pull: true
    networks:
      - name: proxy
    env:
      API_IP_TOKEN: "{{ api_ip_token }}"
      TZ: "Europe/Belgrade"
    volumes:
      - ./data/public_ip_tracker/app.log:/app/app.log:rw
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.public_ip_tracker.entrypoints: "https"
      traefik.http.routers.public_ip_tracker.rule: "{{ node.ip.host }}"
      traefik.http.routers.public_ip_tracker.tls: "true"
      traefik.http.services.public_ip_tracker.loadbalancer.server.port: "{{ node.ip.port }}"
