---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: ./data/public_ip_tracker
    state: directory
    mode: "0744"

- name: Synchronize files
  ansible.posix.synchronize:
    src: ./
    dest: ./data/public_ip_tracker/

- name: Change ownership to "{{ user.name }}"
  ansible.builtin.file:
    path: ./data/public_ip_tracker/
    state: directory
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0744"

- name: Touch current_ip.txt file
  ansible.builtin.file:
    path: ./data/public_ip_tracker/current_ip.txt
    state: touch
    mode: "0600"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Run Docker container from built image
  community.docker.docker_container:
    name: public_ip_tracker
    image: nemanjaslijepcevic/public_ip_tracker:latest
    state: started
    pull: true
    env:
      TELEGRAM_BOT_TOKEN: "{{ telegram_ip.host }}"
      TELEGRAM_CHAT_ID: "{{ telegram_ip.id }}"
      API_IP_TOKEN: "{{ api_ip_token }}"
      TZ: "Europe/Belgrade"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.public_ip_tracker.entrypoints: "https"
      traefik.http.routers.public_ip_tracker.rule: "{{ node.ip.host }}"
      traefik.http.routers.public_ip_tracker.tls: "true"
      traefik.http.services.public_ip_tracker.loadbalancer.server.port: "{{ node.ip.port }}"
