---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: ./data/public_ip_tracker
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0744"

- name: Check if the file exists
  ansible.builtin.stat:
    path: ./data/public_ip_tracker/app.log
  register: file_check

- name: Touch app.log file
  ansible.builtin.file:
    path: ./data/public_ip_tracker/app.log
    state: touch
    mode: "0644"
    owner: "{{ public_ip_tracker_app_uid }}"
    group: "{{ public_ip_tracker_app_gid }}"
  when: not file_check.stat.exists

- name: Enforce app.log ownership and permissions
  ansible.builtin.file:
    path: ./data/public_ip_tracker/app.log
    state: file
    mode: "0644"
    owner: "{{ public_ip_tracker_app_uid }}"
    group: "{{ public_ip_tracker_app_gid }}"

- name: Run Docker container from built image
  community.docker.docker_container:
    name: public_ip_tracker
    image: nemanjaslijepcevic/public_ip_tracker:latest
    state: started
    pull: true
    networks:
      - name: proxy
        ipv4_address: "{{ ip['public_ip_tracker'] }}"
    env:
      API_IP_TOKEN: "{{ api_ip_token }}"
      TZ: "Europe/Belgrade"
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "--header", "Authorization: Bearer {{ api_ip_token }}", "http://127.0.0.1:5000/current_ip"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./data/public_ip_tracker/app.log:/app/app.log:rw
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.public_ip_tracker.entrypoints: "https"
      traefik.http.routers.public_ip_tracker.rule: "{{ node.ip.host }}"
      traefik.http.routers.public_ip_tracker.tls: "true"
      traefik.http.routers.public_ip_tracker.middlewares: "chain-no-auth@file"
      traefik.http.services.public_ip_tracker.loadbalancer.server.port: "{{ node.ip.port }}"

- name: Create logrotate config for public_ip_tracker
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/logrotate.j2"
    dest: "/etc/logrotate.d/public_ip_tracker"
    owner: "root"
    group: "root"
    mode: "0644"
  vars:
    log_path: "{{ ansible_facts.env.PWD }}/data/public_ip_tracker/app.log"
    copytruncate: true
