---
- name: Set permissions on media drives
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ movie_drive }}"
    - "{{ download_drive }}"
  register: media_drive_perms
  failed_when: false

- name: Create directory if they don't exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"
  loop:
    - "./data/radarr"
    - "{{ download_drive }}/Download/complete/radarr"

- name: Deploy radarr container
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart_policy: unless-stopped
    networks:
      - name: proxy
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "Europe/Belgrade"
      RADARR__AUTH__APIKEY: "{{ radarr.api_key }}"
      RADARR__AUTH__METHOD: "External"
      RADARR__AUTH__REQUIRED: "DisabledForLocalAddresses"
      RADARR__SERVER__PORT: "{{ radarr.port }}"
      RADARR__POSTGRES__HOST: "{{ postgres.ip }}"
      RADARR__POSTGRES__PORT: "{{ postgres.port | string }}"
      RADARR__POSTGRES__USER: "{{ postgres.user }}"
      RADARR__POSTGRES__PASSWORD: "{{ postgres.password }}"
      RADARR__POSTGRES__MAINDB: radarr
      RADARR__POSTGRES__LOGDB: radarr-log
      PGSSLMODE: "verify-ca"
      PGSSLCERT: "/postgres-certs/radarr.crt"
      PGSSLKEY: "/postgres-certs/radarr.key"
      PGSSLROOTCERT: "/postgres-certs/ca.crt"
    volumes:
      - ./data/radarr/config:/config
      - ./data/certs:/postgres-certs:ro
      - "{{ movie_drive }}:/movies"
      - "{{ download_drive }}/Download:/downloads"
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.entrypoints: "https"
      traefik.http.routers.radarr.rule: "{{ radarr.host }}"
      traefik.http.routers.radarr.tls: "true"
      traefik.http.routers.radarr.middlewares: "chain-auth@file"
      traefik.http.services.radarr.loadbalancer.server.port: "{{ radarr.port }}"
    healthcheck:
      test: curl --fail http://localhost:7878/ping || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 10s

- name: Wait for Radarr to be ready
  ansible.builtin.uri:
    url: "{{ radarr.url }}/ping"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 10
  delay: 10

- name: Configure Transmission download client
  ansible.builtin.include_tasks: transmission.yml

- name: Configure Telegram notification
  ansible.builtin.include_tasks: telegram.yml

- name: Configure Jellyfin connection
  ansible.builtin.include_tasks: jellyfin.yml

- name: Configure settings
  ansible.builtin.include_tasks: settings.yml
