---
- name: Deploy Plex container
  community.docker.docker_container:
    name: plex
    image: ghcr.io/linuxserver/plex:latest
    restart_policy: unless-stopped
    networks:
      - name: proxy
      - name: streamingMedia
        ipv4_address: "{{ plex.ip }}"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "Europe/Belgrade"
      VERSION: "docker"
    volumes:
      - plex-data:/config
      - "{{ data_drive }}/Muzika:/music"
      - "{{ data_drive }}/Slike:/pictures"
      - "{{ data_drive }}/Snimci:/videos"
      - "{{ movie_drive }}/Filmovi:/Filmovi"
      - "{{ download_drive }}/Download/Watch:/tv"
    labels:
      traefik.enable: "true"
      traefik.http.routers.plex.entrypoints: "https"
      traefik.http.routers.plex.rule: "{{ plex.host }}"
      traefik.http.routers.plex.tls: "true"
      traefik.http.services.plex.loadbalancer.server.port: "{{ plex.port }}"
