- name: Update firewall rules
  ansible.builtin.include_tasks: ufw.yml

- name: "Create directory if they don't exist"
  ansible.builtin.file:
    path: ./data
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: Install fuse-overlayfs
  ansible.builtin.apt:
    name: fuse-overlayfs
    state: present
  when: docker_storage_driver is defined and docker_storage_driver == "fuse-overlayfs"

- name: Prepare docker settings
  ansible.builtin.include_tasks: docker-settings.yml
