---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"
  loop:
    - "./data/traefik"
    - "./data/traefik/rules"
    - "./data/traefik/logs"

- name: Synchronize files
  ansible.posix.synchronize:
    src: ./
    dest: ./data/traefik/
    times: true
    rsync_opts:
      - "--chown={{ user.name }}:{{ user.group }}"
      - "--chmod=755"

- name: Check if acme.json exists
  ansible.builtin.stat:
    path: ./data/traefik/acme.json
  register: file_check

- name: Touch acme.json file
  ansible.builtin.file:
    path: ./data/traefik/acme.json
    state: touch
    mode: "0600"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: not file_check.stat.exists

- name: Catch public IP
  ansible.builtin.uri:
    url: "{{ public_ip_url }}"
    return_content: true
    headers:
      Authorization: "Bearer {{ api_ip_token }}"
  register: public_ip
  run_once: true
  changed_when: false
  check_mode: false
  when: current_host == 'server'

- name: Add public IP to private_ips list
  ansible.builtin.set_fact:
    private_ips: "{{ (private_ips | default([])) + [public_ip.json.ip] }}"
  when: current_host == 'server'

- name: "Generate configuration"
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: ./data/traefik/{{ item }}.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
  loop:
    - traefik
  register: traefik_static_config


- name: "Generate rules"
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: ./data/traefik/rules/{{ item }}.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
  loop:
    - default-whitelist
    - tunnel-whitelist
    - crowdsec-bouncer
    - chain-auth
    - chain-no-auth
    - chain-basic-auth
    - chain-tunnel

- name: "Generate server-only rules (Cloudflare RealIP + GeoBlock + webhook relay)"
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: ./data/traefik/rules/{{ item }}.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
  loop:
    - cloudflarewarp
    - geoblock
    - hooks
  when: current_host == 'server'

- name: Create logrotate config for traefik
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/logrotate.j2"
    dest: "/etc/logrotate.d/traefik"
    owner: "root"
    group: "root"
    mode: "0644"
  vars:
    log_path: "{{ ansible_facts.env.PWD }}/data/traefik/logs/traefik.log"
    copytruncate: true

- name: Create logrotate config for access
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/logrotate.j2"
    dest: "/etc/logrotate.d/traefik-access"
    owner: "root"
    group: "root"
    mode: "0644"
  vars:
    log_path: "{{ ansible_facts.env.PWD }}/data/traefik/logs/access.log"
    copytruncate: true
