---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: "./data/traefik"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: Synchronize files
  ansible.posix.synchronize:
    src: ./
    dest: ./data/traefik/
    times: false
    rsync_opts:
    - "--chown={{ user.name }}:{{ user.group }}" 
    - "--chmod=755"

- name: Check if acme.json exists
  ansible.builtin.stat:
    path: ./data/public_ip_tracker/app.log
  register: file_check

- name: Touch acme.json file
  ansible.builtin.file:
    path: ./data/traefik/acme.json
    state: touch
    mode: "0600"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: not file_check.stat.exists

- name: "Generate traefik.yml"
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: ./data/traefik/traefik.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'

- name: "Generate rules"
  ansible.builtin.template:
    src: "{{ item }}.yml.j2"
    dest: ./data/traefik/rules/{{ item }}.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
  loop:
    - basic-auth
    - default-whitelist
    - docker-metrics

- name: "Generate nas.yml"
  ansible.builtin.template:
    src: nas.yml.j2
    dest: ./data/traefik/rules/nas.yml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
  when: current_host == 'nas'
