---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: ./data/lidarr
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: Deploy Lidarr container
  community.docker.docker_container:
    name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart_policy: unless-stopped
    networks:
      - name: proxy
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "Europe/Belgrade"
    volumes:
      - ./data/lidarr/config:/config
      - "{{ data_drive }}/Muzika:/music"
      - "{{ download_drive }}/Download:/downloads"
    labels:
      traefik.enable: "true"
      traefik.http.routers.lidarr.entrypoints: "https"
      traefik.http.routers.lidarr.rule: "{{ lidarr.host }}"
      traefik.http.routers.lidarr.tls: "true"
      traefik.http.services.lidarr.loadbalancer.server.port: "{{ lidarr.port }}"
