---
- name: "Add {{ db.name }}"
  community.docker.docker_container:
    name: "{{ db.name }}"
    image: mariadb:11
    pull: true
    state: started
    restart_policy: unless-stopped
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    networks:
      - name: proxy
        ipv4_address: "{{ db.static }}"
    volumes:
      - "{{ db.volume }}:/var/lib/mysql"
    env:
      TZ: "Europe/Belgrade"
      MARIADB_ROOT_PASSWORD: "{{ db.pass }}"
