---
- name: "Add {{ db_name }}"
  community.docker.docker_container:
    name: "{{ db_name }}"
    image: mysql:8.4.1
    pull: true
    state: started
    restart_policy: unless-stopped
    command: "--mysql-native-password=ON --server-id={{ db_id }} --log-bin=mysql-bin --binlog-format=row"
    networks:
      - name: proxy
        ipv4_address: "{{ db_static }}"
    volumes:
      - "{{ db_volume }}:/var/lib/mysql"
    env:
      TZ: "Europe/Belgrade"
      MYSQL_ROOT_PASSWORD: "{{ db_pass }}"
