---
- name: Install Adminer
  community.docker.docker_container:
    name: adminer
    image: adminer
    pull: true
    state: started
    restart_policy: unless-stopped
    networks:
      - name: proxy
        ipv4_address: "{{ ip['adminer'] }}"
    env:
      TZ: "Europe/Belgrade"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "-o", "/dev/null", "http://127.0.0.1:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      traefik.enable: "true"
      traefik.http.routers.adminer.entrypoints: "https"
      traefik.http.routers.adminer.rule: "{{ adminer.host }}"
      traefik.http.routers.adminer.tls: "true"
      traefik.http.routers.adminer.middlewares: "chain-auth@file"
      traefik.http.services.adminer.loadbalancer.server.port: "{{ adminer.port }}"
