---
- name: Generate TLS certificates
  ansible.builtin.include_tasks: certs.yml

- name: Generate and distribute client certificates
  ansible.builtin.include_tasks: client_certs.yml

- name: Deploy PostgreSQL container
  ansible.builtin.include_tasks: container.yml
