---
traefik_links:
  static: "172.20.0.6"
  name:
    link: "proxy.example.com"
    host: "Host(`proxy.example.com`)"
    url: "https://proxy.example.com"
    port: "80"
  zero:
    main: "example.com"
    sans: "*.example.com"
  one:
    main: "example2.com"
    sans: "*.example2.com"
  two:
    main: "example3.com"
    sans: "*.example3.com"

cloudflare:
  account: "user@example.com"
  api_token: "changeme"

crowdsec:
  traefik:
    bouncer_key: "changeme"

geoblock_blocked_countries: []

hooks:
  public_host: "hooks.example.com"
  private_host: "https://kestra.example.com"
  connection:
    - name: hook-example
      public_path: "/changeme"
      target_path: "/api/v1/main/executions/webhook"
