---
- name: Create directories if they don't exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "1883"
    group: "1883"
    mode: "0755"
  loop:
    - "./data/mosquitto"
    - "./data/mosquitto/data"
    - "./data/mosquitto/log"
    - "./data/mosquitto/config"

- name: "Copy mosquitto.conf"
  ansible.builtin.copy:
    src: ./mosquitto.conf
    dest: ./data/mosquitto/config/mosquitto.conf
    owner: "1883"
    group: "1883"
    mode: '0644'
  notify: Restart Mosquitto

- name: Check mosquitto password file
  ansible.builtin.stat:
    path: ./data/mosquitto/config/passwd
  register: mosquitto_passwd_stat

- name: Generate mosquitto password file
  ansible.builtin.command:
    cmd: >
      docker run --rm -v {{ ansible_facts.env.PWD }}/data/mosquitto/config:/work
      eclipse-mosquitto mosquitto_passwd -c -b /work/passwd
      {{ mqtt.user }} {{ mqtt.password }}
  when: not mosquitto_passwd_stat.stat.exists
  changed_when: true
  no_log: true
  notify: Restart Mosquitto

- name: Set mosquitto password file permissions
  ansible.builtin.file:
    path: ./data/mosquitto/config/passwd
    owner: "1883"
    group: "1883"
    mode: '0640'

- name: Deploy MQTT container
  community.docker.docker_container:
    name: mosquitto
    image: eclipse-mosquitto:latest
    restart_policy: unless-stopped
    networks:
      - name: proxy
        ipv4_address: "{{ ip['mosquitto'] }}"
    ports:
      - "1883:1883"
    env:
      TZ: "Europe/Belgrade"
    volumes:
      - ./data/mosquitto:/mosquitto
      - ./data/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    labels:
      traefik.enable: "true"
      traefik.http.routers.mosquitto.entrypoints: "https"
      traefik.http.routers.mosquitto.rule: "{{ mqtt.host }}"
      traefik.http.routers.mosquitto.tls: "true"
      traefik.http.services.mosquitto.loadbalancer.server.port: "{{ mqtt.port }}"
    healthcheck:
      test:
        - "CMD"
        - "mosquitto_pub"
        - "-h"
        - "127.0.0.1"
        - "-u"
        - "{{ mqtt.user }}"
        - "-P"
        - "{{ mqtt.password }}"
        - "-t"
        - "healthcheck/ping"
        - "-m"
        - "ok"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
