---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: ./data/prowlarr
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"

- name: Deploy prowlarr container
  community.docker.docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart_policy: unless-stopped
    networks:
      - name: proxy
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "Europe/Belgrade"
    volumes:
      - ./data/prowlarr/config:/config
    labels:
      traefik.enable: "true"
      traefik.http.routers.prowlarr.entrypoints: "https"
      traefik.http.routers.prowlarr.rule: "{{ prowlarr.host }}"
      traefik.http.routers.prowlarr.tls: "true"
      traefik.http.services.prowlarr.loadbalancer.server.port: "{{ prowlarr.port }}"
