---
all:
  vars:
    ansible_private_key_file: "{{ user.private_key_path }}"
    ansible_connection: "ssh"
    ansible_user: "{{ user.name }}"
  children:
    servers:
      hosts:
        primary_server:
          ansible_host: "{{ host.server }}"
          ansible_port: "{{ host.port }}"
    nass:
      hosts:
        primary_nas:
          ansible_host: "{{ host.nas }}"
    monitors:
      hosts:
        primary_monitor:
          ansible_host: "{{ host.monitor }}"
