---
all:
  vars:
    ansible_private_key_file: "{{ user.private_key_path }}"
    ansible_connection: "ssh"
    ansible_user: "{{ user.name }}"
  children:
    servers:
      hosts:
        primary_server:
          ansible_host: "{{ host.server }}"
          ansible_port: "{{ host.port }}"
    nass:
      hosts:
        primary_nas:
          ansible_host: "{{ host.nas }}"
    monitors:
      hosts:
        primary_monitor:
          ansible_host: "{{ host.monitor }}"
    postgres:
      hosts:
        primary_postgres:
          ansible_host: "{{ host.postgres }}"
    netboots:
      hosts:
        primary_netboot:
          ansible_host: "{{ host.netboot }}"
    automations:
      hosts:
        primary_automation:
          ansible_host: "{{ host.automation }}"
    openbaos:
      hosts:
        primary_openbao:
          ansible_host: "{{ host.openbao }}"
