---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: ./data/public_ip_whitelist_updater
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0744"

- name: Check if the file exists
  ansible.builtin.stat:
    path: ./data/public_ip_whitelist_updater/app.log
  register: file_check

- name: Touch app.log file
  ansible.builtin.file:
    path: ./data/public_ip_whitelist_updater/app.log
    state: touch
    mode: "0640"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: not file_check.stat.exists

- name: Enforce app.log ownership and permissions
  ansible.builtin.file:
    path: ./data/public_ip_whitelist_updater/app.log
    state: file
    mode: "0640"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Run Docker container from built image
  community.docker.docker_container:
    name: public_ip_whitelist_updater
    image: nemanjaslijepcevic/public_ip_updater:latest
    state: started
    pull: true
    networks:
      - name: proxy
        ipv4_address: "{{ ip['public_ip_whitelist_updater'] }}"
    dns_servers:
      - "{{ default.dns }}"
    env:
      API_IP_TOKEN: "{{ api_ip_token }}"
      NODE_IP_DOMAIN: "{{ public_ip_url }}"
      TZ: "Europe/Belgrade"
    volumes:
      - ./data/traefik/rules/default-whitelist.yml:/app/configuration.yml:rw
      - ./data/public_ip_whitelist_updater/app.log:/app/app.log:rw
    restart_policy: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "main.py"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 15s

- name: Create logrotate config for whitlist_updater
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/logrotate.j2"
    dest: "/etc/logrotate.d/whitlist_updater"
    owner: "root"
    group: "root"
    mode: "0644"
  vars:
    log_path: "{{ ansible_facts.env.PWD }}/data/public_ip_whitelist_updater/app.log"
