---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: ./data/public_ip_whitelist_updater
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0744"

- name: Check if the file exists
  ansible.builtin.stat:
    path: ./data/public_ip_whitelist_updater/app.log
  register: file_check

- name: Touch app.log file
  ansible.builtin.file:
    path: ./data/public_ip_whitelist_updater/app.log
    state: touch
    mode: "0755"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: not file_check.stat.exists

- name: Run Docker container from built image
  community.docker.docker_container:
    name: public_ip_whitelist_updater
    image: nemanjaslijepcevic/public_ip_updater:latest
    state: started
    pull: true
    env:
      API_IP_TOKEN: "{{ api_ip_token }}"
      NODE_IP_DOMAIN: "{{ public_ip_url }}"
      TZ: "Europe/Belgrade"
    volumes:
      - ./data/traefik/rules/default-whitelist.yml:/app/configuration.yml:rw
      - ./data/public_ip_whitelist_updater/app.log:/app/app.log:rw
    restart_policy: unless-stopped
