- name: Check registered bouncers
  community.docker.docker_container_exec:
    container: crowdsec
    command: cscli bouncers list -o json
  register: crowdsec_bouncers_list
  changed_when: false

- name: Register Cloudflare bouncer key in CrowdSec
  community.docker.docker_container_exec:
    container: crowdsec
    command: cscli bouncers add cloudflare-bouncer --key {{ crowdsec.cloudflare.bouncer_key }}
  when: "'cloudflare-bouncer' not in crowdsec_bouncers_list.stdout"
  changed_when: true

- name: "Generate configuration file"
  ansible.builtin.template:
    src: ./cfg.yaml.j2
    dest: ./data/crowdsec/cfg.yaml
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0640'
  register: cloudflare_bouncer_cfg

- name: Create bouncer-cloudflare
  community.docker.docker_container:
    name: cloudflare-bouncer
    image: crowdsecurity/cloudflare-bouncer
    pull: true
    state: started
    recreate: "{{ cloudflare_bouncer_cfg.changed | default(false) }}"
    restart_policy: unless-stopped
    networks:
      - name: proxy
        ipv4_address: "{{ ip['cloudflare-bouncer'] }}"
    volumes:
      - ./data/crowdsec/cfg.yaml:/etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml
    healthcheck:
      test: ["CMD", "pgrep", "-f", "crowdsec-cloudflare-bouncer"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 15s
