---
- name: Create logrotate config for syslog
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/logrotate.j2"
    dest: "/etc/logrotate.d/syslog"
    owner: "root"
    group: "root"
    mode: "0644"
  vars:
    log_path: "/var/log/syslog"

- name: Clean packages
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Check if a reboot is needed
  register: reboot_required_file
  ansible.builtin.stat:
    path: /var/run/reboot-required

- name: Reboot the system if needed
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: reboot_required_file.stat.exists
