---
- name: Create directory if they don't exist
  ansible.builtin.file:
    path: ./data/log_notification
    state: directory
    mode: "0744"

- name: Change ownership to "{{ user.name }}"
  ansible.builtin.file:
    path: ./data/log_notification/
    state: directory
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0744"

- name: Generate volume mounts for server
  ansible.builtin.set_fact:
    volume_to_mount: "./data/public_ip_whitelist_updater/app.log"
    mount_point: "/app/logs/whitelist.log"
  when: current_host == 'server'

- name: Generate volume mounts for monitor
  ansible.builtin.set_fact:
    volume_to_mount: "./data/public_ip_tracker/app.log"
    mount_point: "/app/logs/public_ip.log"
  when: current_host == 'monitor'

- name: Run Docker container from built image
  community.docker.docker_container:
    name: log_notification
    image: nemanjaslijepcevic/log_notification:latest
    state: started
    pull: true
    env:
      TELEGRAM_BOT_TOKEN: "{{ log_notification.telegram_bot }}"
      TELEGRAM_CHAT_ID: "{{ log_notification.chat_id }}"
      NOTIFICATION_PATTERNS: 'WARNING, EXCEPTION, ERROR, IP has changed'
      TZ: "Europe/Belgrade"
    restart_policy: unless-stopped
    volumes:
      - "{{ volume_to_mount }}:{{ mount_point }}"
