---
- name: "Update NAS"
  hosts: nass
  gather_facts: true
  remote_user: "{{ user.name }}"
  become: true
  vars:
    current_host: "nas"
  roles:
    - { role: common, tags: ['common'] }
    - { role: alloy, tags: ['alloy', 'metrics', 'logs', 'monitoring'] }
    - { role: prepare_smb, tags: ['prepare_smb'] }
    - { role: prepare_postgres, tags: ['prepare_postgres', 'postgres', 'database'] }
    - { role: authelia, tags: ['authelia', 'proxy', 'security'] }
    - { role: traefik, tags: ['traefik', 'proxy', 'security'] }
    - { role: crowdsec, tags: ['crowdsec', 'proxy', 'security'] }
    - { role: filebrowser, tags: ['filebrowser'] }
    - { role: transmission, tags: ['transmission', 'media'] }
    - { role: jellyfin, tags: ['jellyfin', 'media'] }
    - { role: radarr, tags: ['radarr', 'arr', 'media'] }
    - { role: sonarr, tags: ['sonarr', 'arr', 'media'] }
    - { role: lidarr, tags: ['lidarr', 'arr', 'media'] }
    - { role: prowlarr, tags: ['prowlarr', 'arr', 'media'] }
    - { role: bazarr, tags: ['bazarr', 'arr', 'media'] }
    - { role: recyclarr, tags: ['recyclarr', 'arr', 'media'] }
    - { role: seerr, tags: ['seerr', 'arr', 'media'] }
