---
- name: "Update OpenBao"
  hosts: openbaos
  gather_facts: true
  remote_user: "{{ user.name }}"
  become: true
  vars:
    current_host: "openbao"
  roles:
    - { role: common, tags: ['common'] }
    - { role: authelia, tags: ['authelia', 'proxy', 'security'] }
    - { role: traefik, tags: ['traefik', 'proxy', 'security'] }
    - { role: crowdsec, tags: ['crowdsec', 'proxy', 'security'] }
    - { role: openbao, tags: ['openbao', 'secrets'] }
    - { role: alloy, tags: ['alloy', 'metrics', 'logs', 'monitoring'] }
