{
 "title": "Traefik (Flux per-host)",
 "description": "Visualizing Traefik Reverse Proxy Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "nas,server,monitor,netboot,postgres"
   },
   { "name": "sampling", "label": "Sampling", "query": "1m,10m,60m" },
   {
    "name": "service",
    "label": "Service",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"traefik-${host}\", tag: \"service\", predicate: (r) => r._measurement == \"traefik.service.requests.total\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Total request",
   "type": "stat",
   "gridPos": { "y": 0, "w": 4, "h": 9, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"traefik-${host}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"traefik.router.requests.total\" and r._field == \"count\")\n  |> group()\n  |> sum()"
    }
   ]
  },
  {
   "title": "Requests per service",
   "type": "graph",
   "gridPos": { "y": 0, "w": 20, "h": 9, "x": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"traefik-${host}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"traefik.service.requests.total\" and r._field == \"count\")\n  |> filter(fn: (r) => r.service =~ /${service:regex}/)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: ${sampling}, fn: sum, createEmpty: false)\n  |> group(columns: [\"service\"])"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(count_over_time({job=\"traefik\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"traefik-${host}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"traefik.service.request.duration\" and r._field == \"p99\")\n  |> filter(fn: (r) => r.service =~ /${service:regex}/)\n  |> aggregateWindow(every: ${sampling}, fn: mean, createEmpty: false)\n  |> group(columns: [\"service\"])"
    }
   ]
  },
  {
   "title": "Total status code count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"traefik-${host}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"traefik.router.requests.total\" and r._field == \"count\")\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: ${sampling}, fn: sum, createEmpty: false)\n  |> group(columns: [\"code\"])"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"traefik-${host}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"traefik.open.connections\" and r._field == \"value\")\n  |> aggregateWindow(every: ${sampling}, fn: mean, createEmpty: false)\n  |> group(columns: [\"entrypoint\",\"protocol\",\"method\"])"
    }
   ]
  },
  {
   "title": "Traefik JSON Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{job=\"traefik\"} | json | line_format \"{{.OriginStatus}} | {{.time}} | {{.RequestAddr}} | {{.ClientHost}} | {{.RequestMethod}} {{.RequestPath}} {{.RequestProtocol}} | {{.request_User_Agent}}\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "maxLines": 800,
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}