http:
  middlewares:
    chain-auth:
      chain:
        middlewares:
          - default-whitelist
          - crowdsec-bouncer
          - secure-headers
          - rate-limit
          - authelia
